// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDey826Gs6PRFPlNRfgh_oEKSvYR3uAP0s',
    appId: '1:105594208334:web:24349e25656fdbba0f831f',
    messagingSenderId: '105594208334',
    projectId: 'washing-41a92',
    authDomain: 'washing-41a92.firebaseapp.com',
    storageBucket: 'washing-41a92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWc0rRXilDtRYjywXAxJUlJuidRAeQRNM',
    appId: '1:105594208334:android:f8c73f6c12bc23c60f831f',
    messagingSenderId: '105594208334',
    projectId: 'washing-41a92',
    storageBucket: 'washing-41a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4Si9rxsemdOAFgHXC7C79RFCZ5cSUXE',
    appId: '1:105594208334:ios:ed03d1d14d01314b0f831f',
    messagingSenderId: '105594208334',
    projectId: 'washing-41a92',
    storageBucket: 'washing-41a92.firebasestorage.app',
    iosBundleId: 'com.example.carwashapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4Si9rxsemdOAFgHXC7C79RFCZ5cSUXE',
    appId: '1:105594208334:ios:ed03d1d14d01314b0f831f',
    messagingSenderId: '105594208334',
    projectId: 'washing-41a92',
    storageBucket: 'washing-41a92.firebasestorage.app',
    iosBundleId: 'com.example.carwashapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDey826Gs6PRFPlNRfgh_oEKSvYR3uAP0s',
    appId: '1:105594208334:web:fe2e0cb5428792b20f831f',
    messagingSenderId: '105594208334',
    projectId: 'washing-41a92',
    authDomain: 'washing-41a92.firebaseapp.com',
    storageBucket: 'washing-41a92.firebasestorage.app',
  );
}
